Repository gazaskygeeks/Coding-Foundations-course, pull requests merged in 2021-02, with the labels that each got.

#57 Higher order function workshop
  coursebook/Week 05/session-14/higherOrderFunctions.md
Labels: Done

#56 Destructuring workshop
  coursebook/Week 05/session-13/destructuring.md
Labels: Done

#60 Update some points of week4
  coursebook/Week 04/session-09/data-types.md
  coursebook/Week 04/session-09/variables-and-constants.md
  coursebook/Week 04/session-11/loops.md
  coursebook/Week 04/session-11/var-let-const.md
Labels: Done

#61 update some examples at week-5
  coursebook/Week 05/session-14/array-methods.md
Labels: Done

#67 update week-6
  coursebook/Week 06/README.md
  coursebook/Week 06/session-15/README.md
  coursebook/Week 06/session-15/learning-outcomes.md
  coursebook/Week 06/session-15/research-topics.md
  coursebook/Week 06/session-15/resources.md
  coursebook/Week 06/session-16/DOM-manipulations.md
  coursebook/Week 06/session-16/Dom-Exercises.md
  coursebook/Week 06/session-16/Intro-to-DOM.md
  coursebook/Week 06/session-16/README.md
  coursebook/Week 06/session-16/learning-outcomes.md
  coursebook/Week 06/session-16/research-topics.md
  coursebook/Week 06/session-16/resources.md
  coursebook/Week 06/session-17/README.md
  coursebook/Week 06/session-17/learning-outcomes.md
  coursebook/Week 06/session-17/local-storage.md
  coursebook/Week 06/session-17/research-topics.md
  coursebook/Week 06/session-17/resources.md
  coursebook/Week 06/session-17/todo-app.md
Labels: awaiting-review

#66 update Week 5
  coursebook/Week 05/README.md
  coursebook/Week 05/session-12/README.md
  coursebook/Week 05/session-12/exercises.md
  coursebook/Week 05/session-12/functions-scopes.md
  coursebook/Week 05/session-12/intro-to-functions.md
  coursebook/Week 05/session-12/learning-outcomes.md
  coursebook/Week 05/session-12/morning-challenge.md
  coursebook/Week 05/session-12/research-topics.md
  coursebook/Week 05/session-12/resources.md
  coursebook/Week 05/session-13/README.md
  coursebook/Week 05/session-14/README.md
Labels: awaiting-review

#68 First project workshop
  coursebook/Week 03/session-06/README.md
  coursebook/Week 03/session-06/first-project.md
Labels: Done

#70 update week5
  coursebook/Week 05/README.md
  coursebook/Week 05/session-12/README.md
  coursebook/Week 05/session-12/exercises.md
  coursebook/Week 05/session-12/homework.md
  coursebook/Week 05/session-12/javascript-objects.md
  coursebook/Week 05/session-12/learning-outcomes.md
  coursebook/Week 05/session-12/loop.md
  coursebook/Week 05/session-12/morning-challenge.md
  coursebook/Week 05/session-12/puzzle.md
  coursebook/Week 05/session-12/research-topics.md
  coursebook/Week 05/session-12/resources.md
  coursebook/Week 05/session-13/README.md
  coursebook/Week 05/session-13/array-methods.jpg
  coursebook/Week 05/session-13/array-methods.md
  coursebook/Week 05/session-13/arrays.md
  coursebook/Week 05/session-13/exercises.md
  coursebook/Week 05/session-13/homework.md
  coursebook/Week 05/session-13/learning-outcomes.md
  coursebook/Week 05/session-13/loops.md
  coursebook/Week 05/session-13/research-topics.md
  coursebook/Week 05/session-13/research.md
  coursebook/Week 05/session-13/resources.md
  coursebook/Week 05/session-14/JavaScript-while-loop.png
  coursebook/Week 05/session-14/README.md
  coursebook/Week 05/session-14/learning-outcomes.md
  coursebook/Week 05/session-14/resources.md
Labels: awaiting-review

#69 Update Week4
  coursebook/Week 04/README.md
  coursebook/Week 04/session-09/README.md
  coursebook/Week 04/session-09/exercise.md
  coursebook/Week 04/session-09/learning-outcomes.md
  coursebook/Week 04/session-09/operators.md
  coursebook/Week 04/session-09/research-topics.md
  coursebook/Week 04/session-09/resources.md
  coursebook/Week 04/session-10/README.md
  coursebook/Week 04/session-10/exercises.md
  coursebook/Week 04/session-10/intro-to-functions.md
  coursebook/Week 04/session-10/learning-outcomes.md
  coursebook/Week 04/session-10/morning-challenge.md
  coursebook/Week 04/session-10/research-topics.md
  coursebook/Week 04/session-10/resources.md
  coursebook/Week 04/session-10/scopes.md
  coursebook/Week 04/session-10/variables.md
  coursebook/Week 04/session-11/README.md
  coursebook/Week 04/session-11/exercises.md
  coursebook/Week 04/session-11/homework.md
  coursebook/Week 04/session-11/learning-outcomes.md
  coursebook/Week 04/session-11/loop.md
  coursebook/Week 04/session-11/morning-challenge.md
  coursebook/Week 04/session-11/research-topics.md
  coursebook/Week 04/session-11/resources.md
Labels: awaiting-review

#71 update some points at week-1-
  coursebook/Week 01/session-00/intro-to-html.md
  coursebook/Week 01/session-02/assignment.md
  coursebook/Week 01/session-02/introduction-to-git.md
Labels: Done

#72 Week6 update
  coursebook/Week 05/session-14/README.md
  coursebook/Week 05/session-14/problem-solving.md
  coursebook/Week 06/README.md
  coursebook/Week 06/session-15/DOM-manipulations.md
  coursebook/Week 06/session-15/Dom-Exercises.md
  coursebook/Week 06/session-15/Intro-to-DOM.md
  coursebook/Week 06/session-15/README.md
  coursebook/Week 06/session-15/learning-outcomes.md
  coursebook/Week 06/session-15/research-topics.md
  coursebook/Week 06/session-15/resources.md
  coursebook/Week 06/session-16/README.md
  coursebook/Week 06/session-16/learning-outcomes.md
  coursebook/Week 06/session-16/local-storage.md
  coursebook/Week 06/session-16/research-topics.md
  coursebook/Week 06/session-16/resources.md
  coursebook/Week 06/session-16/todo-app.md
  coursebook/Week 06/session-17/README.md
  coursebook/Week 06/session-17/learning-outcomes.md
  coursebook/Week 06/session-17/research-topics.md
  coursebook/Week 06/session-17/resources.md
  coursebook/higher Order Functions.md
Labels: awaiting-review

#73 Update the link of the code along workshop
  coursebook/Week 03/session-06/README.md
Labels: awaiting-review

#74 Update week2-Schechule
  coursebook/Week 02/session-03/README.md
  coursebook/Week 02/session-04/README.md
  coursebook/Week 02/session-05/README.md
  coursebook/Week 02/session-05/animations.md
Labels: awaiting-review

#75 fix fonts file path
  coursebook/Week 02/session-03/README.md
Labels: To Be Merge

#76 update morning challenge
  coursebook/Week 02/session-04/morning-challenge.md
Labels: awaiting-review
